import seaborn as sns
palette = sns.color_palette(['#E69F00', '#56B4E9', '#009E73', '#F0E442',
                             '#0072B2', '#D55E00', '#CC79A7', '#000000'])

job2color = {
    '-'          : 'darkgray', 
    'job_medical':  'steelblue',
    'job_creator': 'darkcyan',
    'employed'   : 'darkolivegreen',
    'job_media'  : 'darkgreen',
    'job_government'  : 'sienna',
    'job_streamer'  : 'slateblue',
    'job_editor'  : 'peru',
    'job_tv'     : 'olive',
    'job_education': 'brown',
    'employed_leader' : 'royalblue',
    'job_research': 'steelblue',
    'job_independent': 'blue',
    'job_service': 'orange',
    'unemployed_student_major': 'green',
    'painter': palette[2],
    'artist': 'olive',
    'massmedia': palette[0],
    'employed_subordinate': 'pink',
    'job_music': 'magenta',
    'job_politician': 'gray',
    'Webnews': palette[1],
    
}

job2paper = {
    '-'          : 'No info', 
    'job_medical': 'Medical doctor',
    'employed'   : 'Employee',
    'massmedia'   : 'Media',
    'job_media'  : 'Journalist',
    'job_government'  : 'Government',
    'job_creator': 'Writer',
    'employed_leader' : 'Manager',
    'job_tv'     : 'Broadcaster',
    'job_education': 'Educators', 
    'job_research': 'Researcher',
    'job_independent': 'Independent',
    'job_service': 'Service',
    'unemployed_student_major': 'Student',
    'employed_subordinate': 'Subordinate',
    'job_music': 'Musician',
    'job_editor': 'Editor',
    'job_streamer': 'Streamer',
    'job_politician': 'Politician',
}

job2paper = {
    '-'          : 'No info', 
    'job_medical': 'Medical doctor',
    'employed'   : 'Employee',
    'massmedia'   : 'TV, Newspaper',
    'job_media'  : 'Journalist',
    'job_government'  : 'Government',
    'job_creator': 'Professional writer',
    'painter': 'Painter',
    'artist': 'Artist',
    'employed_leader' : 'Business owner',
    'job_tv'     : 'Broadcaster',
    'job_education': 'Educators', 
    'job_research': 'Researcher',
    'job_independent': 'Independent',
    'job_service': 'Service',
    'unemployed_student_major': 'Student',
    'employed_subordinate': 'Subordinate',
    'job_music': 'Musician',
    'job_editor': 'Publisher',
    'job_streamer': 'Streamer',
    'Webnews': 'Web news',
    'job_politician': 'Politician',
}